const groceryData = [
  {
    id: 1,
    brand: "Fresho",
    name: "Onion (Loose)",
    price: 35,
    delivery: "Today 7:00 Am to 7:00 PM",
    img: "https://www.bigbasket.com/media/uploads/p/s/10000148_30-fresho-onion.jpg",
  },
  {
    id: 2,
    brand: "Fresho",
    name: "Potato",
    price: 36,
    delivery: "Today 7:00 Am to 7:00 PM",
    img: "https://www.bigbasket.com/media/uploads/p/s/10000159_27-fresho-potato.jpg",
  },
  {
    id: 3,
    brand: "Fresho",
    name: "Tomato (Hybrid)",
    price: 150,
    delivery: "Today 7:00 Am to 7:00 PM",
    img: "https://www.bigbasket.com/media/uploads/p/s/40312600_1-fresho-tomato-hybrid.jpg",
  },
  {
    id: 4,
    brand: "Fresho",
    name: "Carrot - Orange (Loose)",
    price: 98,
    delivery: "Today 7:00 Am to 7:00 PM",
    img: "https://www.bigbasket.com/media/uploads/p/s/10000071_14-fresho-carrot-orange.jpg",
  },
  {
    id: 5,
    brand: "Fresho",
    name: "Laddies - finger (Loose)",
    price: 35,
    delivery: "Today 7:00 Am to 7:00 PM",
    img: "https://www.bigbasket.com/media/uploads/p/s/10000143_14-fresho-ladies-finger.jpg",
  },
  {
    id: 6,
    brand: "Fresho",
    name: "Capsicum - Green",
    price: 65,
    delivery: "Today 7:00 Am to 7:00 PM",
    img: "https://www.bigbasket.com/media/uploads/p/s/10000067_23-fresho-capsicum-green.jpg",
  },
  {
    id: 7,
    brand: "Fresho",
    name: "Banana",
    price: 125,
    delivery: "Today 7:00 Am to 7:00 PM",
    img: "https://www.bigbasket.com/media/uploads/p/s/10000031_21-fresho-banana-yelakki.jpg",
  },
];

export default groceryData;
