const restaurantList = [
  {
    name: "Meghana Foods",
    img: "https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg?auto=compress&cs=tinysrgb&w=800",
    resType: "Biryani, North Indian",
    starRating: 4.4,
    deliveryTime: 40,
    foodCost: 200,
    id: 1,
  },
  {
    name: "Rawat Bhojanalya",
    img: "https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=800",
    resType: "North Indian Veg Food",
    starRating: 4.7,
    deliveryTime: 30,
    foodCost: 250,
    id: 2,
  },
  {
    name: "KFC",
    img: "https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=800",
    resType: "Burger, Fast Food",
    starRating: 3.9,
    deliveryTime: 50,
    foodCost: 300,
    id: 3,
  },
  {
    name: "Pizza Hut",
    img: "https://images.pexels.com/photos/2120483/pexels-photo-2120483.jpeg?auto=compress&cs=tinysrgb&w=800",
    resType: "Pizza, Fast Food",
    starRating: 3.7,
    deliveryTime: 25,
    foodCost: 180,
    id: 4,
  },
  {
    name: "La Pinno Pizza",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ysvhwgn1iluc4j4mmvnc",
    resType: "Pizza, Pastas, Italian",
    starRating: 3.9,
    deliveryTime: 45,
    foodCost: 500,
    id: 5,
  },
  {
    name: "LunchBox - Meals and Thalis",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ywvtndu8hk3mblk14l6q",
    resType: "Biryani, North Indian, Punjabi",
    starRating: 4,
    deliveryTime: 38,
    foodCost: 400,
    id: 6,
  },
  {
    name: "Fassos - Wraps and Rolls",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/af33b81798b11deba338e94b7585d348",
    resType: "Fast Food, Snacks, Kebabs",
    starRating: 4.1,
    deliveryTime: 30,
    foodCost: 300,
    id: 7,
  },
  {
    name: "The Good Bowl",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/htxzcxy0cd03jpqsm31h",
    resType: "North Indian",
    starRating: 4.1,
    deliveryTime: 25,
    foodCost: 600,
    id: 8,
  },
  {
    name: "CakeZone - Pure Veg",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/dc7abc110dbafe0a9bad837a292842dc",
    resType: "Bakery, Desserts, Sweets",
    starRating: 4.3,
    deliveryTime: 20,
    foodCost: 200,
    id: 9,
  },
  {
    name: "Behrouz Biryani",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/49c27c020e946f8f4fc13fdc9038525c",
    resType: "Biryani, Mughlai",
    starRating: 3.6,
    deliveryTime: 50,
    foodCost: 450,
    id: 10,
  },
];

export default restaurantList;
